version: '3.4'

services:

  php:
    image: bitnami/php-fpm:7.3.25
    ports:
      - "9000:9000"
    networks:
      - backbone
    volumes:
      - ./dist:/srv/www/api
      - ./docker/php.ini:/opt/bitnami/php/lib/php.ini

  nginx:
    image: nginx:1.13.8
    ports:
      - "80:80"
    networks:
      - backbone
    volumes:
      - ./dist:/srv/www/api:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

networks:
    backbone:
      driver: bridge